export interface Milk {
    "职业": string,
    "ID": string,
    "祝福": number,
    "一觉": number,
    "三觉": number,
    "其他": number,
    "三攻": number,
    "唱歌后三攻": number,
    "力智总和": number,
    "相对提升伤害": number,
    "双C提升伤害(迫害奶萝)": number,
    "常驻力智": number,
    "常驻提升": number,
    "常驻提升-2C": number,
    "常驻提升倍率": number,
    "爆发提升倍率": number,
    "相对提升伤害-2C": number,
    "力智总和-归一化": number,
    "唱歌后三攻-归一化": number,
    "常驻提升-归一化": number,
    "相对提升伤害-归一化": number,
    "常驻提升-2C-归一化": number,
    "相对提升伤害2C-归一化": number
}